FI.WebAtividadeEntrevista/Controllers/BeneficiarioController.cs
using FI.AtividadeEntrevista.BLL;
using WebAtividadeEntrevista.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FI.AtividadeEntrevista.DML;

namespace WebAtividadeEntrevista.Controllers
{
    public class BeneficiarioController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Incluir(BeneficiarioModel model)
        {
            BoBeneficiario bo = new BoBeneficiario();

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            //Verifica se o CPF é válido - Bianca
            else if (!bo.VerificarValidade(model.CPF))
            {
                return Json("CPF inválido");
            }
            //Verifica se já existe o CPF cadastrado - Bianca 
            else if (bo.VerificarExistencia(model.CPF))
            {
                return Json("CPF já cadastrado");
            }
            else
            {

                model.Id = bo.Incluir(new Beneficiario()
                {                    
                    Nome = model.Nome,                   
                    CPF = model.CPF,
                    IDCLIENTE = model.IDCLIENTE,
                });


                return Json("Cadastro efetuado com sucesso");
            }
        }

        [HttpPost]
        public JsonResult Alterar(BeneficiarioModel model)
        {
            BoBeneficiario bo = new BoBeneficiario();

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                bo.Alterar(new Beneficiario()
                {
                    Id = model.Id,                    
                    Nome = model.Nome, 
                    CPF = model.CPF,
                    IDCLIENTE = model.IDCLIENTE,
                });

                return Json("Cadastro alterado com sucesso");
            }
        }

        [HttpGet]
        public ActionResult Alterar(long id)
        {
            BoBeneficiario bo = new BoBeneficiario();
            Beneficiario beneficiario = bo.Consultar(id);
            Models.BeneficiarioModel model = null;

            if (beneficiario != null)
            {
                model = new BeneficiarioModel()
                {
                    Id = beneficiario.Id,                  
                    Nome = beneficiario.Nome,
                    CPF = beneficiario.CPF,
                    IDCLIENTE = beneficiario.IDCLIENTE
                };


            }

            return View(model);
        }

        [HttpPost]
        public JsonResult BeneficiarioList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                int qtd = 0;
                string campo = string.Empty;
                string crescente = string.Empty;
                string[] array = jtSorting.Split(' ');

                if (array.Length > 0)
                    campo = array[0];

                if (array.Length > 1)
                    crescente = array[1];

                List<Beneficiario> beneficiarios = new BoBeneficiario().Pesquisa(jtStartIndex, jtPageSize, campo, crescente.Equals("ASC", StringComparison.InvariantCultureIgnoreCase), out qtd);

                //Return result to jTable
                return Json(new { Result = "OK", Records = beneficiarios, TotalRecordCount = qtd });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

FI.WebAtividadeEntrevista/Views/Beneficiario/Alterar.cshtml
@model WebAtividadeEntrevista.Models.BeneficiarioModel
@{
    ViewBag.Title = "Alterar Beneficiario";
}
@section scripts{
<script>
        var urlPost = '@Url.Action("Alterar", "Beneficiario", new { area = "" })';
        var obj = @Html.Raw(Json.Encode(Model));
        var urlRetorno = '@Url.Action("Index", "Beneficiario", new { area = "" })';
</script>
    @Scripts.Render("~/bundles/altBeneficiarios")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")

FI.WebAtividadeEntrevista/Views/Beneficiario/Forms.cshtml
@Scripts.Render("~/bundles/mascara") 

<div id="modalBeneficiario" class="modal">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

            </div>
            <div class="modal-body">
                <form id="formCadastroBeneficiario" method="post">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="Nome">Nome:</label>
                                <input required="required" type="text" class="form-control" id="Nome" name="Nome" placeholder="Ex.: João" maxlength="50">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="CPF">CPF:</label>
                                <input required="required" type="text" class="form-control" id="CPF" name="CPF" placeholder="Ex.: 999.999.999-99" maxlength="15">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="pull-right">
                                <button type="submit" class="btn btn-sm btn-success">Salvar</button>
                                @Html.ActionLink("Voltar", "Index", "Beneficiario", new { }, new { @class = "btn btn-sm btn-danger" })
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

FI.WebAtividadeEntrevista/Views/Beneficiario/Incluir.cshtml
@{
    ViewBag.Title = "Cadastrar Beneficiario";
}
@section scripts{
    <script>
        var urlPost = '@Url.Action("Incluir", "Beneficiario", new { area = "" })';
    </script>
    @Scripts.Render("~/bundles/beneficiarios")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")

FI.WebAtividadeEntrevista/Views/Beneficiario/Index.cshtml
@{
    ViewBag.Title = "Beneficiarios";
}
@section scripts{
    <script>

    var urlBeneficiarioList = '@Url.Action("BeneficiarioList", "Beneficiario", new { area = "" })';
    var urlBeneficiarioAlteracao = '@Url.Action("BeneficiarioAlterar", "Beneficiario", new { area = "" })';
    var urlBeneficiarioIncluir = '@Url.Action("BeneficiarioIncluir", "Beneficiario", new { area = "" })';

    </script>
    @Scripts.Render("~/bundles/listBeneficiarios")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.ActionLink("Novo Beneficiario", "Incluir", "Beneficiario", new { }, new { @class = "btn btn-sm btn-primary pull-right" })
<table id="gridBeneficiarios" class="table"></table>